#!/bin/bash

# Variables Declaration
PACKAGE="httpd wget unzip"
SVC="httpd"
URL="### static website template ###"
ART_NAME="###"
TEMPDIR="/tmp/webfiles"

# Detect Linux Distribution
if [ -f /etc/os-release ]; then
    . /etc/os-release
    OS=$ID
else
    echo "Unknown operating system. Exiting..."
    exit 1
fi

# Function for installing packages based on the OS
install_packages() {
    case $OS in
        ubuntu)
            PACKAGE="apache2 wget unzip"
            SVC="apache2"
            sudo apt update -y
            sudo apt install -y $PACKAGE
            ;;
        centos|amzn)
            sudo yum install -y $PACKAGE
            ;;
        *)
            echo "Unsupported OS: $OS"
            exit 1
            ;;
    esac
}

# Function to manage the web service (start, enable)
manage_service() {
    case $OS in
        ubuntu|centos|amzn)
            sudo systemctl start $SVC
            sudo systemctl enable $SVC
            ;;
        *)
            echo "Unsupported service manager on OS: $OS"
            exit 1
            ;;
    esac
}

# Install dependencies
echo "########################"
echo "Installing packages. "
echo "########################"
install_packages
echo

# Start & Enable Service
echo "########################"
echo "Start & Enable HTTPD/Apache2 Service"
echo "########################"
manage_service
echo

# Creating Temp Directory
echo "########################"
echo "Starting Artifact Deployment"
echo "########################"
mkdir -p $TEMPDIR
cd $TEMPDIR

echo
wget $URL > /dev/null
unzip $ART_NAME.zip > /dev/null
sudo cp -r $ART_NAME/* /var/www/html/
echo

# Restart Service
echo "########################"
echo "Restarting HTTPD/Apache2 Service"
echo "########################"
sudo systemctl restart $SVC
echo

# Clean Up
echo "########################"
echo "Removing Temp Files"
echo "########################"
rm -rf $TEMPDIR
echo
echo "-----------------------"
echo "         DONE!         "
echo "-----------------------"
echo
sudo systemctl status $SVC
echo
ls /var/www/html
