Vagrant.configure("2") do |config|
  # Setting OS
  config.vm.box = "ubuntu/focal64"

  # Network configuration
  config.vm.network "private_network", type: "dhcp"

  # Syncing local project folder with VM
  config.vm.synced_folder ".", "/vagrant"

  # Provisioning
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y python3 python3-pip
  SHELL
end

